---

  - name: Install Oracle Java Repo Installer Repository
    apt_repository: repo='{{ item }}' update-cache=yes
    become: yes
    with_items:
      - ppa:webupd8team/java

  - name: Accept the Oracle license prompt
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
    become: yes

  - name: Install Oracle Java 6
    apt: pkg=oracle-java6-set-default
    when: oracle_java_version == 6
    become: yes

  - name: Install Oracle Java 7
    apt: pkg=oracle-java7-set-default
    when: oracle_java_version == 7
    become: yes

  - name: Install Oracle Java 8
    apt: pkg=oracle-java8-set-default
    when: oracle_java_version == 8
    become: yes
